### ISSUE TITLE
qshenidam fails to launch

### ISSUE THREAD

**Issue by ryandesign** [stendardo/shenidam#3]
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.1
BuildVersion:   15B42
```

```
$ port installed shenidam
The following ports are currently installed:
  shenidam @1.0_0+universal (active)
```

```
$ qshenidam
Traceback (most recent call last):
  File "/opt/local/lib/shenidam/python//qshenidam.py", line 482, in <module>
    frame = Frame()
  File "/opt/local/lib/shenidam/python//qshenidam.py", line 329, in __init__
    import qshenidam_icon as qi
  File "/opt/local/lib/shenidam/python/qshenidam_icon.py", line 1
    __data__ = 'iVBORw0KGgoAAAANSUhEUgAAAEEAAABBCAYAAACO98lFAAAABHNCSVQICAgIfAhkiAAAAAlw
                                                                                       ^
SyntaxError: EOL while scanning string literal
```

**Comment by stendardo** [comment]
Should be fixed in Master

**Comment by ryandesign** [comment]
Thanks, 17b82ef10bf33b411863d2493a272ee218aeb6e1 does fix it.
